/**
 * Demo / Simulation Data Provider
 * 
 * Generates realistic-looking trading dashboard data so the frontend
 * renders beautifully even when no live backend is available.
 * All numbers are internally consistent and plausible.
 */

// ── Helpers ──────────────────────────────────────────────────────────

function randomBetween(min: number, max: number): number {
	return Math.random() * (max - min) + min;
}

function randomInt(min: number, max: number): number {
	return Math.floor(randomBetween(min, max + 1));
}

function pickRandom<T>(arr: T[]): T {
	return arr[Math.floor(Math.random() * arr.length)];
}

function generateId(): string {
	return Math.random().toString(36).slice(2, 10) + Date.now().toString(36);
}

function isoAgo(minutesAgo: number): string {
	return new Date(Date.now() - minutesAgo * 60_000).toISOString();
}

function generateEquityCurve(points: number, startVal: number, drift: number): number[] {
	const curve: number[] = [startVal];
	for (let i = 1; i < points; i++) {
		const change = curve[i - 1] * (drift + (Math.random() - 0.48) * 0.02);
		curve.push(Math.max(curve[i - 1] + change, startVal * 0.7));
	}
	return curve.map(v => Math.round(v * 100) / 100);
}

// ── Constants ────────────────────────────────────────────────────────

const STRATEGY_NAMES = [
	'Momentum Breakout Alpha', 'Mean Reversion Grid', 'Volatility Squeeze Hunter',
	'Trend Rider EMA-Cross', 'RSI Divergence Sniper', 'Bollinger Bounce Pro',
	'VWAP Scalper Elite', 'Order Flow Tracker', 'Range Compression Play',
	'Adaptive ATR Trailer', 'Dual Timeframe Momentum', 'Liquidity Sweep Catcher',
	'Ichimoku Cloud Rider', 'Fibonacci Retracement Pro', 'Market Structure Break',
	'Volume Profile Fade', 'Correlation Pair Arbitrage', 'Regime Switch Detector',
];

const SYMBOLS = [
	'BTC/USDT', 'ETH/USDT', 'SOL/USDT', 'BNB/USDT', 'XRP/USDT',
	'AVAX/USDT', 'DOGE/USDT', 'ADA/USDT', 'MATIC/USDT', 'LINK/USDT',
	'DOT/USDT', 'ARB/USDT', 'OP/USDT', 'APT/USDT', 'SUI/USDT',
];

const TIMEFRAMES = ['1m', '5m', '15m', '1h', '4h', '1d'];

const LIFECYCLE_STATES = [
	'discovered', 'backtested', 'validated', 'paper_trading',
	'soak_test', 'live_candidate', 'live_deployed', 'retired',
];

const ACTIVITY_TYPES = [
	'lifecycle', 'autopilot_job', 'signal', 'backtest_complete',
	'risk_alert', 'data_ingestion', 'strategy_promoted', 'agent_action',
];

// ── Demo Data Generators ─────────────────────────────────────────────

export function getDemoDashboardOverview() {
	return {
		kpis: {
			total_tested: randomInt(1247, 1890),
			best_sharpe: Math.round(randomBetween(2.1, 3.8) * 100) / 100,
			active_scans: randomInt(2, 8),
			signals_today: randomInt(12, 47),
			pipeline_count: randomInt(34, 78),
			data_coverage: Math.round(randomBetween(94.5, 99.2) * 10) / 10,
		},
		lifecycle_counts: {
			discovered: randomInt(120, 340),
			backtested: randomInt(80, 200),
			validated: randomInt(30, 90),
			paper_trading: randomInt(8, 24),
			soak_test: randomInt(3, 12),
			live_candidate: randomInt(2, 7),
			live_deployed: randomInt(1, 5),
			retired: randomInt(400, 800),
		},
		blocked_count: randomInt(0, 3),
		last_ingestion_at: isoAgo(randomInt(1, 15)),
		autopilot: {
			initialized: true,
			running: true,
			paused: false,
			run_id: `ap-${generateId()}`,
			worker_concurrency: 4,
			active_workers: randomInt(1, 4),
			queued_jobs: randomInt(0, 12),
			dead_letter_jobs: 0,
			last_tick_error: null,
			health_ok: true,
			disabled_reason: null,
		},
		timestamp: new Date().toISOString(),
	};
}

export function getDemoDashboardActivity(limit = 40) {
	const items = [];
	const templates = [
		{ type: 'lifecycle', title: 'Strategy promoted', detail: '{name} moved from backtested → validated' },
		{ type: 'autopilot_job', title: 'Backtest completed', detail: '{name} on {symbol} {tf} — Sharpe {sharpe}' },
		{ type: 'signal', title: 'Long signal triggered', detail: '{name} fired buy on {symbol} at ${price}' },
		{ type: 'signal', title: 'Short signal triggered', detail: '{name} fired sell on {symbol} at ${price}' },
		{ type: 'data_ingestion', title: 'Data sync complete', detail: '{symbol} 1m candles updated — {count} new bars' },
		{ type: 'lifecycle', title: 'Strategy retired', detail: '{name} failed soak test — max DD exceeded threshold' },
		{ type: 'agent_action', title: 'Brain decision', detail: 'Promoted {name} to paper_trading based on robustness score {score}' },
		{ type: 'risk_alert', title: 'Risk threshold warning', detail: 'Portfolio correlation spike detected — {value}% across {count} strategies' },
		{ type: 'backtest_complete', title: 'Scan batch finished', detail: 'Scan #{scanId} tested {count} variants — {winners} passed filters' },
		{ type: 'lifecycle', title: 'Strategy discovered', detail: '{name} generated by evolution engine — pending backtest' },
		{ type: 'autopilot_job', title: 'Robustness check passed', detail: '{name} passed Monte Carlo + walk-forward validation' },
		{ type: 'strategy_promoted', title: 'Live deployment', detail: '{name} deployed to Hyperliquid testnet — paper trading active' },
	];

	for (let i = 0; i < Math.min(limit, 40); i++) {
		const tmpl = pickRandom(templates);
		const name = pickRandom(STRATEGY_NAMES);
		const symbol = pickRandom(SYMBOLS);
		const tf = pickRandom(TIMEFRAMES);
		const detail = tmpl.detail
			.replace('{name}', name)
			.replace('{symbol}', symbol)
			.replace('{tf}', tf)
			.replace('{sharpe}', (randomBetween(0.8, 2.5)).toFixed(2))
			.replace('{price}', randomBetween(100, 70000).toFixed(2))
			.replace('{count}', String(randomInt(50, 2400)))
			.replace('{winners}', String(randomInt(3, 28)))
			.replace('{scanId}', String(randomInt(100, 999)))
			.replace('{value}', (randomBetween(60, 92)).toFixed(1))
			.replace('{score}', (randomBetween(7.2, 9.6)).toFixed(1));

		items.push({
			type: tmpl.type,
			id: generateId(),
			ts: isoAgo(i * randomInt(3, 20)),
			title: tmpl.title,
			detail,
			strategy_id: generateId(),
		});
	}
	return items;
}

export function getDemoDashboardWinners(limit = 10) {
	const winners = [];
	for (let i = 0; i < limit; i++) {
		const sharpe = Math.round(randomBetween(1.2, 3.5) * 100) / 100;
		const totalReturn = Math.round(randomBetween(15, 180) * 100) / 100;
		const winRate = Math.round(randomBetween(48, 72) * 100) / 100;
		const maxDD = Math.round(randomBetween(3, 18) * 100) / 100;
		winners.push({
			id: generateId(),
			strategy_name: STRATEGY_NAMES[i % STRATEGY_NAMES.length],
			display_name: null,
			symbol: pickRandom(SYMBOLS),
			timeframe: pickRandom(TIMEFRAMES),
			sharpe_ratio: sharpe,
			total_return: totalReturn,
			monthly_return_pct: Math.round(randomBetween(2, 12) * 100) / 100,
			annualized_return_pct: Math.round(randomBetween(30, 200) * 100) / 100,
			max_drawdown: maxDD,
			win_rate: winRate,
			total_trades: randomInt(80, 1200),
			profit_factor: Math.round(randomBetween(1.3, 3.2) * 100) / 100,
			sortino_ratio: Math.round(sharpe * randomBetween(1.1, 1.6) * 100) / 100,
			calmar_ratio: Math.round((totalReturn / maxDD) * 100) / 100,
			source: pickRandom(['scanner', 'evolution', 'manual', 'crucible']),
			scan_id: generateId(),
			lifecycle_strategy_id: generateId(),
			tier: pickRandom(['S', 'A', 'B']),
			mini_equity: generateEquityCurve(30, 10000, 0.003),
		});
	}
	// Sort by sharpe descending
	winners.sort((a, b) => b.sharpe_ratio - a.sharpe_ratio);
	return winners;
}

export function getDemoHealthResponse() {
	return {
		status: 'ok',
		version: '2.4.1',
		uptime_seconds: randomInt(3600, 864000),
		demo_mode: true,
	};
}

export function getDemoSettings() {
	return {
		exchange: 'hyperliquid',
		mode: 'paper',
		risk_max_drawdown_pct: 15,
		risk_max_position_size_pct: 5,
		risk_kill_switch_enabled: true,
		autopilot_enabled: true,
		autopilot_max_concurrent: 4,
		notification_discord_enabled: false,
		notification_email_enabled: false,
		has_credentials: false,
		has_llm_key: false,
		demo_mode: true,
	};
}

// ── Exported demo mode flag ──────────────────────────────────────────

let _demoMode = false;

export function isDemoMode(): boolean {
	return _demoMode;
}

export function enableDemoMode(): void {
	_demoMode = true;
	if (typeof window !== 'undefined') {
		console.info(
			'%c🎯 Kronos-Quant Demo Mode Active%c — Showing simulated data',
			'color: #8b5cf6; font-weight: bold; font-size: 14px;',
			'color: #6b7280; font-size: 12px;'
		);
	}
}
